"""
Generate 5 descriptions per category for COCO and Cityscapes using GPT-4o.
Output: pl_dc/modeling/category_descriptions.py

Usage:
    export OPENAI_API_KEY=sk-...
    python tools/generate_category_descriptions.py
"""

import os
import json
from openai import OpenAI

COCO_CLASSES = [
    'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
    'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign',
    'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
    'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag',
    'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite',
    'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
    'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon',
    'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot',
    'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant',
    'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote',
    'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink',
    'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
    'hair drier', 'toothbrush',
]

CITYSCAPES_CLASSES = [
    'person', 'rider', 'car', 'truck', 'bus', 'train', 'motorcycle', 'bicycle',
]

PROMPT_TEMPLATE = (
    "List {k} descriptions with key properties to describe the {cls} in terms of "
    "appearance, color, shape, size, or material, etc. These descriptions will help "
    "visually distinguish the {cls} from other classes in the same dataset. "
    "The other classes in this dataset are: {other_classes}. "
    "Each description should follow the format: 'a {cls}. it + descriptive contexts.' "
    "Return a JSON array of {k} strings, nothing else."
)

K = 5


def query_gpt(client: OpenAI, cls: str, all_classes: list[str]) -> list[str]:
    other_classes = ", ".join(c for c in all_classes if c != cls)
    prompt = PROMPT_TEMPLATE.format(k=K, cls=cls, other_classes=other_classes)
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
    )
    content = response.choices[0].message.content.strip()
    # strip markdown code fences if present
    if content.startswith("```"):
        content = content.split("```")[1]
        if content.startswith("json"):
            content = content[4:]
    descriptions = json.loads(content)
    assert len(descriptions) == K, f"Expected {K} descriptions for '{cls}', got {len(descriptions)}"
    return descriptions


def generate_descriptions(client: OpenAI, classes: list[str]) -> dict[str, list[str]]:
    result = {}
    for i, cls in enumerate(classes):
        print(f"  [{i+1}/{len(classes)}] {cls} ...", flush=True)
        result[cls] = query_gpt(client, cls, classes)
    return result


def write_output(coco_desc: dict, cityscapes_desc: dict, out_path: str):
    lines = [
        "# Auto-generated by tools/generate_category_descriptions.py",
        "# Format: each value is a list of 5 descriptions for that category.",
        "# Used by DICC (Dynamic Instance Category Correction) in trainer.py.",
        "",
        "COCO_CATEGORY_DESCRIPTIONS = {",
    ]
    for cls, descs in coco_desc.items():
        lines.append(f"    {cls!r}: [")
        for d in descs:
            lines.append(f"        {d!r},")
        lines.append("    ],")
    lines += ["}", "", "CITYSCAPES_CATEGORY_DESCRIPTIONS = {"]
    for cls, descs in cityscapes_desc.items():
        lines.append(f"    {cls!r}: [")
        for d in descs:
            lines.append(f"        {d!r},")
        lines.append("    ],")
    lines += ["}", ""]
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"\nSaved to {out_path}")


def main():
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise EnvironmentError("OPENAI_API_KEY is not set.")

    # client = OpenAI(api_key=api_key)
    client = OpenAI(
        base_url="https://api.getgoapi.com/v1",
        api_key=api_key,
    )
    out_path = os.path.join(
        os.path.dirname(__file__), "..", "pl_dc", "modeling", "category_descriptions.py"
    )
    out_path = os.path.normpath(out_path)

    print("Generating COCO descriptions ...")
    coco_desc = generate_descriptions(client, COCO_CLASSES)

    print("Generating Cityscapes descriptions ...")
    cityscapes_desc = generate_descriptions(client, CITYSCAPES_CLASSES)

    write_output(coco_desc, cityscapes_desc, out_path)


if __name__ == "__main__":
    main()
